let timelineData = [];
document.addEventListener("DOMContentLoaded", async () => { try { const data = await loadAllData(); timelineData = buildTimelineItems(data); renderTimeline(timelineData); setupTimelineControls(); } catch (error) { document.getElementById("timeline").innerHTML = `<div class="error">${error.message}</div>`; console.error(error); } });
function buildTimelineItems(data) {
  const items = [];
  data.timelineEvents.forEach(event => { const lodge = data.lodgeMap.get(event.LodgeID); items.push({ date: event.EventDate, type: event.EventType || "Other", title: event.EventTitle || "Timeline event", description: event.EventDescription || "", lodgeId: event.LodgeID, lodgeName: lodge ? lodgeDisplayName(lodge) : event.LodgeID }); });
  data.lodges.forEach(lodge => { if (lodge.ConsecrationDate) items.push({ date: lodge.ConsecrationDate, type: "Consecrated", title: `${lodgeDisplayName(lodge)} consecrated`, description: lodge.ShortHistory || "", lodgeId: lodge.LodgeID, lodgeName: lodgeDisplayName(lodge) }); if (lodge.ClosureDate) items.push({ date: lodge.ClosureDate, type: "Closed", title: `${lodgeDisplayName(lodge)} closed`, description: "", lodgeId: lodge.LodgeID, lodgeName: lodgeDisplayName(lodge) }); });
  return items.filter(item => item.date).sort((a, b) => String(a.date).localeCompare(String(b.date)));
}
function setupTimelineControls() { document.getElementById("timelineSearch").addEventListener("input", applyTimelineFilters); document.getElementById("eventTypeFilter").addEventListener("change", applyTimelineFilters); }
function applyTimelineFilters() { const search = document.getElementById("timelineSearch").value.trim().toLowerCase(); const type = document.getElementById("eventTypeFilter").value.trim().toLowerCase(); const filtered = timelineData.filter(item => { const searchText = `${item.date} ${item.type} ${item.title} ${item.description} ${item.lodgeName}`.toLowerCase(); return (!search || searchText.includes(search)) && (!type || String(item.type).toLowerCase() === type); }); renderTimeline(filtered); }
function renderTimeline(items) { const container = document.getElementById("timeline"); if (!items.length) { container.innerHTML = "<p>No timeline events found.</p>"; return; } container.innerHTML = items.map(item => `<article class="timeline-item"><div class="timeline-date">${safeText(item.date)}</div><h2 class="timeline-title">${safeText(item.title)}</h2><p class="muted">${safeText(item.type)} · <a href="lodge.html?id=${encodeURIComponent(item.lodgeId)}">${safeText(item.lodgeName)}</a></p>${item.description ? `<p>${item.description}</p>` : ""}</article>`).join(""); }
